# Site settings
title: arts@ADDINGHAM
email: arts@addingham.net
description: > # this means to ignore newlines until "baseurl:"
  Resources
baseurl:  "/arts/"
url:  "https://www.addingham.net/arts/" 
 
# Build settings
markdown: kramdown
